[package]
name = "grant_identity_proof"
type = "bin"
authors = [""]
proving_backend = ".honk"

[dependencies]
schnorr = { tag = "v0.4.0", git = "https://github.com/noir-lang/schnorr" }
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }
