// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./interfaces/INoirVerifier.sol";

/// @title StubNoirVerifier
/// @notice HACKATHON DEMO ONLY — accepts any proof.
///         Replace with the real UltraHonk verifier generated by `bb contract`
///         before going to production.
contract StubNoirVerifier is INoirVerifier {
    function verify(
        bytes calldata /* proof */,
        bytes32[] calldata /* publicInputs */
    ) external pure override returns (bool) {
        return true;
    }
}
